name: 라이브 환경 배포

on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 라이브 서버 배포
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.PROJECT_DIR_LIVE }}
            git pull origin prod
            sudo docker compose -f docker-compose.yml -f docker-compose.prod.yml build --no-cache app
            sudo docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d app
            sudo docker image prune -f
